conventions:
  - path: FacilityApi/Facility/conventions/facility-dotnet-package
    settings:
      nuget-rules:
        - packages: [OmniSharp.Extensions.LanguageServer]
          version: "0.19.7"
pull-request:
  reviewers:
    - ejball
