name: Release

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'


jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Install .NET
      uses: actions/setup-dotnet@v5
    - name: Restore
      run: ./build.ps1 restore
    - name: Build
      run: ./build.ps1 build --skip restore
    - name: Package
      if: runner.os == 'Windows'
      run: ./build.ps1 package --skip build
    - name: Upload package artifacts
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v7
      with:
        name: FacilityLanguageServer
        path: release/*.zip

  release:
    name: Release
    runs-on: windows-latest
    needs: build
    if: github.repository_owner == 'FacilityApi' && github.ref == 'refs/heads/master'
    steps:
    - name: Check out code
      uses: actions/checkout@v6
    - name: Install .NET
      uses: actions/setup-dotnet@v5
    - name: Download packages
      uses: actions/download-artifact@v8
      with:
        name: FacilityLanguageServer
        path: release
    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create ${{ github.event.push.tag }} release/*.zip